# fly.toml for fantasy-basic-backend
app = "fantasy-basic-backend"
primary_region = "mia"

# ========================
# Build configuration
# ========================
[build]
  # Use a Node.js image for building your backend
  image = "node:20"  

# ========================
# HTTP service
# ========================
[http_service]
  internal_port = 8080
  force_https = true

# ========================
# VM configuration
# ========================
[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1